// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    workspace_id, actor_user_id, actor_token_id, action,
    resource_type, resource_id, metadata, ip_address, user_agent
)
VALUES (
    $1,
    $6::uuid,
    $7::uuid,
    $2, $3,
    $8::uuid,
    $4,
    $9::inet,
    $5
)
`

type CreateAuditLogParams struct {
	WorkspaceID  uuid.UUID
	Action       string
	ResourceType string
	Metadata     []byte
	UserAgent    string
	ActorUserID  *uuid.UUID
	ActorTokenID *uuid.UUID
	ResourceID   *uuid.UUID
	IpAddress    *netip.Addr
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.WorkspaceID,
		arg.Action,
		arg.ResourceType,
		arg.Metadata,
		arg.UserAgent,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.ResourceID,
		arg.IpAddress,
	)
	return err
}

const listAuditActions = `-- name: ListAuditActions :many
SELECT DISTINCT action FROM audit_logs
WHERE workspace_id = $1
ORDER BY action
`

// Powers the filter dropdowns in the activity feed without a hardcoded list.
func (q *Queries) ListAuditActions(ctx context.Context, workspaceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAuditActions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.workspace_id, a.actor_user_id, a.actor_token_id, a.action,
       a.resource_type, a.resource_id, a.metadata,
       host(a.ip_address) AS ip_address, a.user_agent, a.created_at,
       coalesce(u.email, '') AS actor_email,
       coalesce(t.name, '')  AS actor_token_name
FROM audit_logs a
LEFT JOIN users u ON u.id = a.actor_user_id
LEFT JOIN access_tokens t ON t.id = a.actor_token_id
WHERE a.workspace_id = $1
  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::uuid IS NULL OR a.actor_user_id = $4::uuid)
  AND ($5::text IS NULL OR a.resource_type = $5::text)
  AND ($6::uuid IS NULL OR a.resource_id = $6::uuid)
  AND (
        $7::timestamptz IS NULL
        OR (a.created_at, a.id) < ($7::timestamptz, $8::uuid)
      )
ORDER BY a.created_at DESC, a.id DESC
LIMIT $2
`

type ListAuditLogsParams struct {
	WorkspaceID     uuid.UUID
	Limit           int32
	Action          *string
	ActorUserID     *uuid.UUID
	ResourceType    *string
	ResourceID      *uuid.UUID
	BeforeCreatedAt *time.Time
	BeforeID        *uuid.UUID
}

type ListAuditLogsRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ActorUserID    *uuid.UUID
	ActorTokenID   *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     *uuid.UUID
	Metadata       []byte
	IpAddress      string
	UserAgent      string
	CreatedAt      time.Time
	ActorEmail     string
	ActorTokenName string
}

// Keyset pagination rather than OFFSET: the feed is append-heavy, and an
// offset scan would both slow down and skip rows as new entries arrive while
// a user pages. The (created_at, id) tuple matches the covering index and is
// unique, so no row is ever seen twice or missed.
//
// Every filter is optional; passing NULL disables it.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.WorkspaceID,
		arg.Limit,
		arg.Action,
		arg.ActorUserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorUserID,
			&i.ActorTokenID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.ActorTokenName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
