// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AccessToken struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	TokenHash     []byte
	Prefix        string
	Scopes        []string
	IpAllowlist   []netip.Addr
	RateLimitRpm  int32
	ExpiresAt     *time.Time
	RevokedAt     *time.Time
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
}

type AuditLog struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	ActorUserID  *uuid.UUID
	ActorTokenID *uuid.UUID
	Action       string
	ResourceType string
	ResourceID   *uuid.UUID
	Metadata     []byte
	IpAddress    *netip.Addr
	UserAgent    string
	CreatedAt    time.Time
}

type Environment struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	Rank      int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UserAgent string
	IpAddress *netip.Addr
}

type Secret struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	EnvironmentID  uuid.UUID
	Key            string
	Description    string
	CurrentVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      *uuid.UUID
	DeletedAt      *time.Time
}

type SecretVersion struct {
	ID         uuid.UUID
	SecretID   uuid.UUID
	Version    int32
	WrappedDek []byte
	Nonce      []byte
	Ciphertext []byte
	Comment    string
	CreatedAt  time.Time
	CreatedBy  *uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
}
