// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, rank)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, rank, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ProjectID uuid.UUID
	Name      string
	Rank      int32
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ProjectID, arg.Name, arg.Rank)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, slug, description, created_at, updated_at
`

type CreateProjectParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
}

type CreateProjectRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const environmentNameExists = `-- name: EnvironmentNameExists :one
SELECT EXISTS (
    SELECT 1 FROM environments WHERE project_id = $1 AND name = $2
)
`

type EnvironmentNameExistsParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) EnvironmentNameExists(ctx context.Context, arg EnvironmentNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, environmentNameExists, arg.ProjectID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, name, rank, created_at, updated_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, name, slug, description, created_at, updated_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

type GetProjectRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT e.id, e.project_id, e.name, e.rank, e.created_at, e.updated_at,
       count(s.id) AS secret_count
FROM environments e
LEFT JOIN secrets s ON s.environment_id = e.id AND s.deleted_at IS NULL
WHERE e.project_id = $1
GROUP BY e.id
ORDER BY e.rank, e.name
`

type ListEnvironmentsRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Rank        int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	SecretCount int64
}

// Environments are returned in promotion order, which is also the order the
// UI displays them in.
func (q *Queries) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, name, slug, description, created_at, updated_at
FROM projects
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY name
`

type ListProjectsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSlugExists = `-- name: ProjectSlugExists :one
SELECT EXISTS (
    SELECT 1 FROM projects
    WHERE workspace_id = $1 AND slug = $2 AND deleted_at IS NULL
)
`

type ProjectSlugExistsParams struct {
	WorkspaceID uuid.UUID
	Slug        string
}

func (q *Queries) ProjectSlugExists(ctx context.Context, arg ProjectSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectSlugExists, arg.WorkspaceID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete: audit entries and version history keep referring to this row,
// so it must survive even though it disappears from every listing.
func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, name, slug, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

type UpdateProjectRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
