// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error
	// Bumps the version pointer, but only if the caller's expected version is
	// still current. A zero row count means someone else wrote first, which the
	// service reports as a version conflict rather than silently overwriting.
	BumpSecretVersion(ctx context.Context, arg BumpSecretVersionParams) (int32, error)
	// Unconditional bump, for writes that do not carry an expected version.
	BumpSecretVersionUnchecked(ctx context.Context, arg BumpSecretVersionUncheckedParams) (int32, error)
	// ---------------------------------------------------------------------------
	// Master key rotation
	// ---------------------------------------------------------------------------
	CountSecretVersions(ctx context.Context) (int64, error)
	CountWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// ip_allowlist and scopes are cast to text[] on the way in and out so the Go
	// layer works with plain strings and owns the parsing into netip.Prefix. That
	// keeps address validation in one tested place instead of splitting it between
	// Go and PostgreSQL.
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (CreateAccessTokenRow, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (CreateSecretRow, error)
	// ---------------------------------------------------------------------------
	// Versions
	// ---------------------------------------------------------------------------
	CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) (CreateSecretVersionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	EmailExists(ctx context.Context, email string) (bool, error)
	EnvironmentNameExists(ctx context.Context, arg EnvironmentNameExistsParams) (bool, error)
	GetAccessToken(ctx context.Context, id uuid.UUID) (GetAccessTokenRow, error)
	// Looks a token up by digest. Revocation and expiry are checked in Go rather
	// than here so that the middleware can tell the two apart when logging.
	GetAccessTokenByHash(ctx context.Context, tokenHash []byte) (GetAccessTokenByHashRow, error)
	// Fetches a refresh token only if it is currently usable. Doing the revocation
	// and expiry checks in SQL means a stale token can never be mistaken for a
	// live one by a caller that forgets to check.
	GetActiveRefreshToken(ctx context.Context, tokenHash []byte) (GetActiveRefreshTokenRow, error)
	// Resolves the value a secret currently holds. Ordering by version rather
	// than by created_at keeps this correct even if two versions land in the same
	// clock tick.
	GetCurrentSecretVersion(ctx context.Context, secretID uuid.UUID) (SecretVersion, error)
	GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error)
	GetProject(ctx context.Context, id uuid.UUID) (GetProjectRow, error)
	GetSecret(ctx context.Context, id uuid.UUID) (GetSecretRow, error)
	GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (GetSecretByKeyRow, error)
	GetSecretVersion(ctx context.Context, arg GetSecretVersionParams) (SecretVersion, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetWorkspaceForUser(ctx context.Context, arg GetWorkspaceForUserParams) (GetWorkspaceForUserRow, error)
	// The single source of truth for "what may this user do here". Every
	// authorisation decision resolves through this one query.
	GetWorkspaceRole(ctx context.Context, arg GetWorkspaceRoleParams) (string, error)
	GetWorkspaceRoleByEnvironment(ctx context.Context, arg GetWorkspaceRoleByEnvironmentParams) (GetWorkspaceRoleByEnvironmentRow, error)
	// Resolves a project's workspace and the caller's role there in one round
	// trip, so nested resources can be authorised without walking the hierarchy.
	GetWorkspaceRoleByProject(ctx context.Context, arg GetWorkspaceRoleByProjectParams) (GetWorkspaceRoleByProjectRow, error)
	GetWorkspaceRoleBySecret(ctx context.Context, arg GetWorkspaceRoleBySecretParams) (GetWorkspaceRoleBySecretRow, error)
	GetWorkspaceRoleByToken(ctx context.Context, arg GetWorkspaceRoleByTokenParams) (GetWorkspaceRoleByTokenRow, error)
	ListAccessTokens(ctx context.Context, projectID uuid.UUID) ([]ListAccessTokensRow, error)
	// Powers the filter dropdowns in the activity feed without a hardcoded list.
	ListAuditActions(ctx context.Context, workspaceID uuid.UUID) ([]string, error)
	// Keyset pagination rather than OFFSET: the feed is append-heavy, and an
	// offset scan would both slow down and skip rows as new entries arrive while
	// a user pages. The (created_at, id) tuple matches the covering index and is
	// unique, so no row is ever seen twice or missed.
	//
	// Every filter is optional; passing NULL disables it.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// Loads every current value in an environment in one query, for promotion and
	// for CI/CD pulls. DISTINCT ON picks the highest version per secret, which
	// avoids issuing one query per secret.
	ListCurrentSecretValues(ctx context.Context, environmentID uuid.UUID) ([]ListCurrentSecretValuesRow, error)
	// Environments are returned in promotion order, which is also the order the
	// UI displays them in.
	ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]ListEnvironmentsRow, error)
	ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]ListProjectsRow, error)
	// History for the UI: metadata plus the author's email, without ciphertext,
	// since the history list never reveals values.
	ListSecretVersions(ctx context.Context, secretID uuid.UUID) ([]ListSecretVersionsRow, error)
	// Walks every stored version in id order for rewrapping. Keyset pagination is
	// used rather than OFFSET so a rotation over a large table stays linear, and
	// so it can be resumed from the last id it reported.
	//
	// Only the wrapped key is selected: rotation never touches the ciphertext, so
	// there is no reason to read it into the process.
	ListSecretVersionsForRotation(ctx context.Context, arg ListSecretVersionsForRotationParams) ([]ListSecretVersionsForRotationRow, error)
	// Metadata only. Values are never included in a listing: revealing one is a
	// separate, individually audited request.
	ListSecrets(ctx context.Context, environmentID uuid.UUID) ([]ListSecretsRow, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	// Lists the workspaces a user belongs to, carrying their role so the caller
	// does not need a second query to decide what to render.
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	ProjectSlugExists(ctx context.Context, arg ProjectSlugExistsParams) (bool, error)
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error
	RevokeAccessToken(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash []byte) error
	SecretKeyExists(ctx context.Context, arg SecretKeyExistsParams) (bool, error)
	// Soft delete: audit entries and version history keep referring to this row,
	// so it must survive even though it disappears from every listing.
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) error
	// Recorded on a best-effort basis after a successful authentication. It is
	// deliberately not part of the request transaction: a failure to record
	// last use must never fail the request itself.
	TouchAccessToken(ctx context.Context, id uuid.UUID) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateSecretDescription(ctx context.Context, arg UpdateSecretDescriptionParams) error
	UpdateSecretVersionWrappedDEK(ctx context.Context, arg UpdateSecretVersionWrappedDEKParams) error
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error
	WorkspaceSlugExists(ctx context.Context, slug string) (bool, error)
}

var _ Querier = (*Queries)(nil)
