// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpSecretVersion = `-- name: BumpSecretVersion :one
UPDATE secrets
SET current_version = current_version + 1,
    updated_at      = now(),
    updated_by      = $3::uuid
WHERE id = $1 AND current_version = $2 AND deleted_at IS NULL
RETURNING current_version
`

type BumpSecretVersionParams struct {
	ID             uuid.UUID
	CurrentVersion int32
	UpdatedBy      *uuid.UUID
}

// Bumps the version pointer, but only if the caller's expected version is
// still current. A zero row count means someone else wrote first, which the
// service reports as a version conflict rather than silently overwriting.
func (q *Queries) BumpSecretVersion(ctx context.Context, arg BumpSecretVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpSecretVersion, arg.ID, arg.CurrentVersion, arg.UpdatedBy)
	var current_version int32
	err := row.Scan(&current_version)
	return current_version, err
}

const bumpSecretVersionUnchecked = `-- name: BumpSecretVersionUnchecked :one
UPDATE secrets
SET current_version = current_version + 1,
    updated_at      = now(),
    updated_by      = $2::uuid
WHERE id = $1 AND deleted_at IS NULL
RETURNING current_version
`

type BumpSecretVersionUncheckedParams struct {
	ID        uuid.UUID
	UpdatedBy *uuid.UUID
}

// Unconditional bump, for writes that do not carry an expected version.
func (q *Queries) BumpSecretVersionUnchecked(ctx context.Context, arg BumpSecretVersionUncheckedParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpSecretVersionUnchecked, arg.ID, arg.UpdatedBy)
	var current_version int32
	err := row.Scan(&current_version)
	return current_version, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (project_id, environment_id, key, description, current_version, updated_by)
VALUES ($1, $2, $3, $4, 0, $5::uuid)
RETURNING id, project_id, environment_id, key, description, current_version,
          created_at, updated_at, updated_by
`

type CreateSecretParams struct {
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Key           string
	Description   string
	UpdatedBy     *uuid.UUID
}

type CreateSecretRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	EnvironmentID  uuid.UUID
	Key            string
	Description    string
	CurrentVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      *uuid.UUID
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (CreateSecretRow, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Key,
		arg.Description,
		arg.UpdatedBy,
	)
	var i CreateSecretRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.Description,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createSecretVersion = `-- name: CreateSecretVersion :one

INSERT INTO secret_versions (secret_id, version, wrapped_dek, nonce, ciphertext, comment, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7::uuid)
RETURNING id, secret_id, version, comment, created_at, created_by
`

type CreateSecretVersionParams struct {
	SecretID   uuid.UUID
	Version    int32
	WrappedDek []byte
	Nonce      []byte
	Ciphertext []byte
	Comment    string
	CreatedBy  *uuid.UUID
}

type CreateSecretVersionRow struct {
	ID        uuid.UUID
	SecretID  uuid.UUID
	Version   int32
	Comment   string
	CreatedAt time.Time
	CreatedBy *uuid.UUID
}

// ---------------------------------------------------------------------------
// Versions
// ---------------------------------------------------------------------------
func (q *Queries) CreateSecretVersion(ctx context.Context, arg CreateSecretVersionParams) (CreateSecretVersionRow, error) {
	row := q.db.QueryRow(ctx, createSecretVersion,
		arg.SecretID,
		arg.Version,
		arg.WrappedDek,
		arg.Nonce,
		arg.Ciphertext,
		arg.Comment,
		arg.CreatedBy,
	)
	var i CreateSecretVersionRow
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.Version,
		&i.Comment,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getCurrentSecretVersion = `-- name: GetCurrentSecretVersion :one
SELECT id, secret_id, version, wrapped_dek, nonce, ciphertext, comment, created_at, created_by
FROM secret_versions
WHERE secret_id = $1
ORDER BY version DESC
LIMIT 1
`

// Resolves the value a secret currently holds. Ordering by version rather
// than by created_at keeps this correct even if two versions land in the same
// clock tick.
func (q *Queries) GetCurrentSecretVersion(ctx context.Context, secretID uuid.UUID) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentSecretVersion, secretID)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.Version,
		&i.WrappedDek,
		&i.Nonce,
		&i.Ciphertext,
		&i.Comment,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT id, project_id, environment_id, key, description, current_version,
       created_at, updated_at, updated_by
FROM secrets
WHERE id = $1 AND deleted_at IS NULL
`

type GetSecretRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	EnvironmentID  uuid.UUID
	Key            string
	Description    string
	CurrentVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      *uuid.UUID
}

func (q *Queries) GetSecret(ctx context.Context, id uuid.UUID) (GetSecretRow, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i GetSecretRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.Description,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT id, project_id, environment_id, key, description, current_version,
       created_at, updated_at, updated_by
FROM secrets
WHERE environment_id = $1 AND key = $2 AND deleted_at IS NULL
`

type GetSecretByKeyParams struct {
	EnvironmentID uuid.UUID
	Key           string
}

type GetSecretByKeyRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	EnvironmentID  uuid.UUID
	Key            string
	Description    string
	CurrentVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      *uuid.UUID
}

func (q *Queries) GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (GetSecretByKeyRow, error) {
	row := q.db.QueryRow(ctx, getSecretByKey, arg.EnvironmentID, arg.Key)
	var i GetSecretByKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.Description,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSecretVersion = `-- name: GetSecretVersion :one
SELECT id, secret_id, version, wrapped_dek, nonce, ciphertext, comment, created_at, created_by
FROM secret_versions
WHERE secret_id = $1 AND version = $2
`

type GetSecretVersionParams struct {
	SecretID uuid.UUID
	Version  int32
}

func (q *Queries) GetSecretVersion(ctx context.Context, arg GetSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRow(ctx, getSecretVersion, arg.SecretID, arg.Version)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.Version,
		&i.WrappedDek,
		&i.Nonce,
		&i.Ciphertext,
		&i.Comment,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listCurrentSecretValues = `-- name: ListCurrentSecretValues :many
SELECT DISTINCT ON (s.id)
       s.id AS secret_id, s.key, s.project_id, s.environment_id,
       v.version, v.wrapped_dek, v.nonce, v.ciphertext
FROM secrets s
JOIN secret_versions v ON v.secret_id = s.id
WHERE s.environment_id = $1 AND s.deleted_at IS NULL
ORDER BY s.id, v.version DESC
`

type ListCurrentSecretValuesRow struct {
	SecretID      uuid.UUID
	Key           string
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Version       int32
	WrappedDek    []byte
	Nonce         []byte
	Ciphertext    []byte
}

// Loads every current value in an environment in one query, for promotion and
// for CI/CD pulls. DISTINCT ON picks the highest version per secret, which
// avoids issuing one query per secret.
func (q *Queries) ListCurrentSecretValues(ctx context.Context, environmentID uuid.UUID) ([]ListCurrentSecretValuesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentSecretValues, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentSecretValuesRow{}
	for rows.Next() {
		var i ListCurrentSecretValuesRow
		if err := rows.Scan(
			&i.SecretID,
			&i.Key,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Version,
			&i.WrappedDek,
			&i.Nonce,
			&i.Ciphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersions = `-- name: ListSecretVersions :many
SELECT v.id, v.secret_id, v.version, v.comment, v.created_at, v.created_by,
       coalesce(u.email, '') AS created_by_email
FROM secret_versions v
LEFT JOIN users u ON u.id = v.created_by
WHERE v.secret_id = $1
ORDER BY v.version DESC
`

type ListSecretVersionsRow struct {
	ID             uuid.UUID
	SecretID       uuid.UUID
	Version        int32
	Comment        string
	CreatedAt      time.Time
	CreatedBy      *uuid.UUID
	CreatedByEmail string
}

// History for the UI: metadata plus the author's email, without ciphertext,
// since the history list never reveals values.
func (q *Queries) ListSecretVersions(ctx context.Context, secretID uuid.UUID) ([]ListSecretVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSecretVersions, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretVersionsRow{}
	for rows.Next() {
		var i ListSecretVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.Version,
			&i.Comment,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, project_id, environment_id, key, description, current_version,
       created_at, updated_at, updated_by
FROM secrets
WHERE environment_id = $1 AND deleted_at IS NULL
ORDER BY key
`

type ListSecretsRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	EnvironmentID  uuid.UUID
	Key            string
	Description    string
	CurrentVersion int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UpdatedBy      *uuid.UUID
}

// Metadata only. Values are never included in a listing: revealing one is a
// separate, individually audited request.
func (q *Queries) ListSecrets(ctx context.Context, environmentID uuid.UUID) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Key,
			&i.Description,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretKeyExists = `-- name: SecretKeyExists :one
SELECT EXISTS (
    SELECT 1 FROM secrets
    WHERE environment_id = $1 AND key = $2 AND deleted_at IS NULL
)
`

type SecretKeyExistsParams struct {
	EnvironmentID uuid.UUID
	Key           string
}

func (q *Queries) SecretKeyExists(ctx context.Context, arg SecretKeyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, secretKeyExists, arg.EnvironmentID, arg.Key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteSecret = `-- name: SoftDeleteSecret :exec
UPDATE secrets
SET deleted_at = now(), updated_by = $2::uuid
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteSecretParams struct {
	ID        uuid.UUID
	UpdatedBy *uuid.UUID
}

func (q *Queries) SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) error {
	_, err := q.db.Exec(ctx, softDeleteSecret, arg.ID, arg.UpdatedBy)
	return err
}

const updateSecretDescription = `-- name: UpdateSecretDescription :exec
UPDATE secrets
SET description = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateSecretDescriptionParams struct {
	ID          uuid.UUID
	Description string
}

func (q *Queries) UpdateSecretDescription(ctx context.Context, arg UpdateSecretDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateSecretDescription, arg.ID, arg.Description)
	return err
}
