// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccessToken = `-- name: CreateAccessToken :one

INSERT INTO access_tokens (
    project_id, environment_id, name, token_hash, prefix,
    scopes, ip_allowlist, rate_limit_rpm, expires_at, created_by
)
VALUES (
    $1, $2, $3, $4, $5,
    $7::text[], $8::text[]::inet[], $6,
    $9::timestamptz, $10::uuid
)
RETURNING id, project_id, environment_id, name, prefix,
          scopes::text[] AS scopes,
          ip_allowlist::text[] AS ip_allowlist,
          rate_limit_rpm, expires_at, revoked_at, last_used_at, created_at, created_by
`

type CreateAccessTokenParams struct {
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	TokenHash     []byte
	Prefix        string
	RateLimitRpm  int32
	Scopes        []string
	IpAllowlist   []string
	ExpiresAt     *time.Time
	CreatedBy     *uuid.UUID
}

type CreateAccessTokenRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Prefix        string
	Scopes        []string
	IpAllowlist   []string
	RateLimitRpm  int32
	ExpiresAt     *time.Time
	RevokedAt     *time.Time
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
}

// ip_allowlist and scopes are cast to text[] on the way in and out so the Go
// layer works with plain strings and owns the parsing into netip.Prefix. That
// keeps address validation in one tested place instead of splitting it between
// Go and PostgreSQL.
func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (CreateAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.RateLimitRpm,
		arg.Scopes,
		arg.IpAllowlist,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateAccessTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.IpAllowlist,
		&i.RateLimitRpm,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, project_id, environment_id, name, prefix,
       scopes::text[] AS scopes,
       ip_allowlist::text[] AS ip_allowlist,
       rate_limit_rpm, expires_at, revoked_at, last_used_at, created_at, created_by
FROM access_tokens
WHERE id = $1
`

type GetAccessTokenRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Prefix        string
	Scopes        []string
	IpAllowlist   []string
	RateLimitRpm  int32
	ExpiresAt     *time.Time
	RevokedAt     *time.Time
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
}

func (q *Queries) GetAccessToken(ctx context.Context, id uuid.UUID) (GetAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, getAccessToken, id)
	var i GetAccessTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.IpAllowlist,
		&i.RateLimitRpm,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT t.id, t.project_id, t.environment_id, t.name, t.prefix,
       t.scopes::text[] AS scopes,
       t.ip_allowlist::text[] AS ip_allowlist,
       t.rate_limit_rpm, t.expires_at, t.revoked_at, t.last_used_at,
       t.created_at, t.created_by,
       p.workspace_id
FROM access_tokens t
JOIN projects p ON p.id = t.project_id
WHERE t.token_hash = $1 AND p.deleted_at IS NULL
`

type GetAccessTokenByHashRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Prefix        string
	Scopes        []string
	IpAllowlist   []string
	RateLimitRpm  int32
	ExpiresAt     *time.Time
	RevokedAt     *time.Time
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
	WorkspaceID   uuid.UUID
}

// Looks a token up by digest. Revocation and expiry are checked in Go rather
// than here so that the middleware can tell the two apart when logging.
func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash []byte) (GetAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i GetAccessTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.IpAllowlist,
		&i.RateLimitRpm,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.WorkspaceID,
	)
	return i, err
}

const listAccessTokens = `-- name: ListAccessTokens :many
SELECT id, project_id, environment_id, name, prefix,
       scopes::text[] AS scopes,
       ip_allowlist::text[] AS ip_allowlist,
       rate_limit_rpm, expires_at, revoked_at, last_used_at, created_at, created_by
FROM access_tokens
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListAccessTokensRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Name          string
	Prefix        string
	Scopes        []string
	IpAllowlist   []string
	RateLimitRpm  int32
	ExpiresAt     *time.Time
	RevokedAt     *time.Time
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	CreatedBy     *uuid.UUID
}

func (q *Queries) ListAccessTokens(ctx context.Context, projectID uuid.UUID) ([]ListAccessTokensRow, error) {
	rows, err := q.db.Query(ctx, listAccessTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessTokensRow{}
	for rows.Next() {
		var i ListAccessTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.IpAllowlist,
			&i.RateLimitRpm,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessToken = `-- name: RevokeAccessToken :one
UPDATE access_tokens
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id
`

func (q *Queries) RevokeAccessToken(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAccessToken, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const touchAccessToken = `-- name: TouchAccessToken :exec
UPDATE access_tokens
SET last_used_at = now()
WHERE id = $1
`

// Recorded on a best-effort basis after a successful authentication. It is
// deliberately not part of the request transaction: a failure to record
// last use must never fail the request itself.
func (q *Queries) TouchAccessToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAccessToken, id)
	return err
}
