// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const countWorkspaceOwners = `-- name: CountWorkspaceOwners :one
SELECT count(*) FROM workspace_members
WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, owner_id, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name    string
	Slug    string
	OwnerID uuid.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceForUser = `-- name: GetWorkspaceForUser :one
SELECT w.id, w.name, w.slug, w.owner_id, w.created_at, w.updated_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE w.id = $1 AND m.user_id = $2
`

type GetWorkspaceForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkspaceForUserRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
}

func (q *Queries) GetWorkspaceForUser(ctx context.Context, arg GetWorkspaceForUserParams) (GetWorkspaceForUserRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForUser, arg.ID, arg.UserID)
	var i GetWorkspaceForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getWorkspaceRole = `-- name: GetWorkspaceRole :one
SELECT role
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// The single source of truth for "what may this user do here". Every
// authorisation decision resolves through this one query.
func (q *Queries) GetWorkspaceRole(ctx context.Context, arg GetWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspaceRoleByEnvironment = `-- name: GetWorkspaceRoleByEnvironment :one
SELECT p.workspace_id, p.id AS project_id, m.role
FROM environments e
JOIN projects p ON p.id = e.project_id
JOIN workspace_members m ON m.workspace_id = p.workspace_id
WHERE e.id = $1 AND m.user_id = $2 AND p.deleted_at IS NULL
`

type GetWorkspaceRoleByEnvironmentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkspaceRoleByEnvironmentRow struct {
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Role        string
}

func (q *Queries) GetWorkspaceRoleByEnvironment(ctx context.Context, arg GetWorkspaceRoleByEnvironmentParams) (GetWorkspaceRoleByEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleByEnvironment, arg.ID, arg.UserID)
	var i GetWorkspaceRoleByEnvironmentRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID, &i.Role)
	return i, err
}

const getWorkspaceRoleByProject = `-- name: GetWorkspaceRoleByProject :one
SELECT p.workspace_id, m.role
FROM projects p
JOIN workspace_members m ON m.workspace_id = p.workspace_id
WHERE p.id = $1 AND m.user_id = $2 AND p.deleted_at IS NULL
`

type GetWorkspaceRoleByProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkspaceRoleByProjectRow struct {
	WorkspaceID uuid.UUID
	Role        string
}

// Resolves a project's workspace and the caller's role there in one round
// trip, so nested resources can be authorised without walking the hierarchy.
func (q *Queries) GetWorkspaceRoleByProject(ctx context.Context, arg GetWorkspaceRoleByProjectParams) (GetWorkspaceRoleByProjectRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleByProject, arg.ID, arg.UserID)
	var i GetWorkspaceRoleByProjectRow
	err := row.Scan(&i.WorkspaceID, &i.Role)
	return i, err
}

const getWorkspaceRoleBySecret = `-- name: GetWorkspaceRoleBySecret :one
SELECT p.workspace_id, p.id AS project_id, s.environment_id, m.role
FROM secrets s
JOIN projects p ON p.id = s.project_id
JOIN workspace_members m ON m.workspace_id = p.workspace_id
WHERE s.id = $1 AND m.user_id = $2 AND s.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetWorkspaceRoleBySecretParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkspaceRoleBySecretRow struct {
	WorkspaceID   uuid.UUID
	ProjectID     uuid.UUID
	EnvironmentID uuid.UUID
	Role          string
}

func (q *Queries) GetWorkspaceRoleBySecret(ctx context.Context, arg GetWorkspaceRoleBySecretParams) (GetWorkspaceRoleBySecretRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleBySecret, arg.ID, arg.UserID)
	var i GetWorkspaceRoleBySecretRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Role,
	)
	return i, err
}

const getWorkspaceRoleByToken = `-- name: GetWorkspaceRoleByToken :one
SELECT p.workspace_id, m.role
FROM access_tokens t
JOIN projects p ON p.id = t.project_id
JOIN workspace_members m ON m.workspace_id = p.workspace_id
WHERE t.id = $1 AND m.user_id = $2
`

type GetWorkspaceRoleByTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkspaceRoleByTokenRow struct {
	WorkspaceID uuid.UUID
	Role        string
}

func (q *Queries) GetWorkspaceRoleByToken(ctx context.Context, arg GetWorkspaceRoleByTokenParams) (GetWorkspaceRoleByTokenRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleByToken, arg.ID, arg.UserID)
	var i GetWorkspaceRoleByTokenRow
	err := row.Scan(&i.WorkspaceID, &i.Role)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.workspace_id, m.user_id, u.email, u.name, m.role, m.created_at
FROM workspace_members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.created_at
`

type ListWorkspaceMembersRow struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Email       string
	Name        string
	Role        string
	CreatedAt   time.Time
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.owner_id, w.created_at, w.updated_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at DESC
`

type ListWorkspacesForUserRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
}

// Lists the workspaces a user belongs to, carrying their role so the caller
// does not need a second query to decide what to render.
func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const workspaceSlugExists = `-- name: WorkspaceSlugExists :one
SELECT EXISTS (SELECT 1 FROM workspaces WHERE slug = $1)
`

func (q *Queries) WorkspaceSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
